---

version: "3.9"

services:
  demo-cluster-00:
    image: 'postgres'
    container_name: 'demo-cluster-00'
    user: '1001:1001'
    restart: 'always'
    ports:         #- "host_port:container_port" 
      - '5555:5432'
    command: 'postgres -c shared_preload_libraries=auto_explain,pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200' 
    environment:
      POSTGRES_USER: 'dbuser'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - '/opt/demo/data/:/var/lib/postgresql/data'
      - '/opt/demo/temp/:/tmp/' 
    networks:
      db_demo_net:
        ipv4_address: '175.20.0.6'  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --quiet --dbname=dbuser --username=dbuser || exit 1"] 
      interval: '2s'
      timeout: '10s'
      retries: '10'
      start_period: '30s'

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'demo-pgadmin'
    restart: 'always'
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 's@khromoy.net' 
      PGADMIN_DEFAULT_PASSWORD: 'changeme'
    volumes:
      - '/opt/demo/pgadmin-data/:/var/lib/pgadmin'      
    networks:
      db_demo_net:
        ipv4_address: '175.20.0.2'
    healthcheck:
       test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
       interval: 10s
       timeout: 10s
       start_period: 160s
       retries: 3

networks:
  db_demo_net:
    ipam:
      driver: 'default'
      config:
        - subnet: '175.20.0.0/24'        
